server:
  port: 8080

spring:
  config:
    import: classpath:application-db.yml

  datasource:
    url: jdbc:mariadb://${dev-db.host}:${dev-db.port}/${dev-db.name}?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: ${dev-db.username}
    password: ${dev-db.password}

  jpa:
    hibernate:
      ddl-auto: create

  flask:
    base-url: ${dev-db.flaskUrl}