server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://${prod-db.host}:${prod-db.port}/${prod-db.name}?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: ${prod-db.username}
    password: ${prod-db.password}

  jpa:
    properties:
      hibernate:
        format_sql: true            # SQL 보기 좋게 출력
        use_sql_comments: true      # SQL 생성시 주석 포함
        highlight_sql: true         # SQL 색깔
        hbm2ddl.auto: validate
    open-in-view: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  header: "Authorization"
  prefix: "Bearer "
  secret: Y2hvcHBhLWRvbnQtYml0ZS1tZS1zcHJpbmctYm9vdC1qd3QtdGVzdC1zZWNyZXQta2V5LWNob3BwYS1kb250LWJpdGUtbWUtc3ByaW5nLWJvb3Qtand0LXRlc3Qtc2VjcmV0LWtleQo=
  tokenExpirationTime: 18000

project:
  folderPath: "files/"
