# Local(로컬 환경, default), Dev(개발 환경), Prod(운영 환경)
# ex))))) java -jar test-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod

spring:
  profiles:
    default: local
    include: token
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/exception
    fallback-to-system-locale: false
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 10
---
spring:
  config:
    activate:
      on-profile: local, dev, prod