spring:
  config:
    import: classpath:application-db.yml

  datasource:
    url: jdbc:mariadb://${prod-db.host}:${prod-db.port}/${prod-db.name}?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: ${prod-db.username}
    password: ${prod-db.password}

  jpa:
    properties:
      hibernate:
        format_sql: true            # SQL 보기 좋게 출력
        highlight_sql: true         # SQL 색깔
        hbm2ddl.auto: validate
    open-in-view: true
    show-sql: true

project:
  folderPath: "/app/files/"